services:
  slmasr:
    image: harbor.suanleme.cn/admin/slmasr:v2
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./modelscope:/root/.cache/modelscope
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
